### ISSUE TITLE
when using the dotnet tool "--runner-version" is required

### ISSUE THREAD

**Issue by Phiph** [ChristopherHX/runner.server#162]
Hi there,

Version: dotnet 3.11.2

When attempting to run the tool without the `--runner-version 3.217.1` command it would attempt to download a version that is no longer available to download, and throw an exception. 

I've opted to use version `3.217.1` of the runner as I found it in these lines

https://github.com/ChristopherHX/runner.server/blob/2877d334a1c2a3ff10002650b225252d20da4697/src/Runner.Client/Program.cs#L1111-L1116

Exception:

```
/Users/phiph/.local/share/gharun/azagent/2.213.2/bin/Agent.Listener executable not found locally
Downloading from https://vstsagentpackage.azureedge.net/agent/2.213.2/vsts-agent-osx-arm64-2.213.2.tar.gz to /Users/phiph/.local/share/gharun/azagent/2.213.2
Unhandled exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Runner.Client.ExternalToolHelper.DownloadTool(String link, String destDirectory, CancellationToken token, String tarextraopts, Boolean unwrap) in /home/runner/work/runner.server/runner.server/src/Runner.Client/ExternalToolHelper.cs:line 76
   at Runner.Client.ExternalToolHelper.GetAgent(String name, String version, CancellationToken token) in /home/runner/work/runner.server/runner.server/src/Runner.Client/ExternalToolHelper.cs:line 189
   at Runner.Client.Program.<>c__DisplayClass27_0.<<Main>b__4>d.MoveNext() in /home/runner/work/runner.server/runner.server/src/Runner.Client/Program.cs:line 1083
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by Phiph** [comment]
> Ah you have a m1 mac, azure devops agents 2.x didn't had mac arm64 releases due to .netcore 3.x.

I do yeah, that makes a lot of sense!

Where is it getting the 2.213.2 version from - I couldn't see it in the code.

**Comment by Phiph** [comment]
Ahh cheers Chris, I didn't think to check the tags.
