### ISSUE TITLE
Unexpected type 'StringToken' encountered while reading 'bool'. The type 'BooleanToken' was expected.

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#264]
Apparently, the following syntax is valid:

```yaml
trigger: none

parameters:
- name: present
  type: string
  default: ''

steps:
- checkout: none
- ${{ if parameters.present }}: 
  - script: exit 0
```

Produces the following stacktrace:

```text
Exception: The template is not valid. (self)/pipeline.yml (Line: 10, Col: 3): FileId: 1 Line: 10 Column: 3 Unexpected type 'StringToken' encountered while reading 'bool'. The type 'BooleanToken' was expected.,    at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check() in /home/runner/work/runner.server/runner.server/src/Sdk/DTObjectTemplating/ObjectTemplating/TemplateValidationErrors.cs:line 88
   at AzureDevops.ReadTemplate(Context context, String filenameAndRef, Dictionary`2 cparameters, String schemaName) in /home/runner/work/runner.server/runner.server/src/Sdk/AzurePipelines/AzureDevops.cs:line 618
   at Runner.Client.Program.AzurePipelinesExpander.ExpandCurrentPipeline(Parameters handle, String currentFileName) in /home/runner/work/runner.server/runner.server/src/Runner.Client/Program.cs:line 828
   at Runner.Client.Program.<>c__DisplayClass29_2.<<Main>b__17>d.MoveNext() in /home/runner/work/runner.server/runner.server/src/Runner.Client/Program.cs:line 1710
```

**Comment by bryanbcook** [comment]
This seems pretty deep into the template parser. I've traced it to the [`TemplateUnraveler:896`](https://github.com/ChristopherHX/runner.server/blob/d2082c949e4cf945b64b2ef9f17ec64cb864e56b/src/Sdk/DTObjectTemplating/ObjectTemplating/TemplateUnraveler.cs#L896C1-L898C21)
